name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "45 0 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: hao-jiang.54a08e82 # optional, but default will use the same from github
